# Generated by Django 4.0.6 on 2022-07-14 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adboard_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='title')),
                ('description', tinymce.models.HTMLField(max_length=8190, verbose_name='description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('category', models.ManyToManyField(to='adboard_site.category', verbose_name='categoriues')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
